#!/usr/bin/env ruby
# frozen_string_literal: true

BLANK_SIZE = 23
ARRAY_FULL_SIZE = 3

def files_to_matrix
  files_from_current_directory = Dir.glob('*')
  files = files_from_current_directory.each_slice(3).to_a
  # 配列内の要素が3つに揃うように空白を追加
  files.each do |array_to_three|
    array_to_three.concat([''] * (ARRAY_FULL_SIZE - array_to_three.size)) if array_to_three.size < ARRAY_FULL_SIZE
  end

  # 各要素を縦に並べる
  files.transpose.each do |row|
    print_file_to_display(row)
  end
end

def print_file_to_display(files)
  max_length = files.map(&:length).max
  files.each do |file|
    print "#{file.ljust(max_length + 1)}#{' ' * (BLANK_SIZE - max_length)}"
  end
  puts
end

files_to_matrix
